name = "water-me-please"
main = "index.js"
compatibility_date = "2024-09-01"

[vars]
GITHUB_REPO = "damiththa/water-me-please"

[env.production]
name = "water-me-please"
[env.production.vars]
GITHUB_REPO = "damiththa/water-me-please"
EVENT_TYPE = "flic_water_all"

[env.dev]
name = "water-me-please-dev"
[env.dev.vars]
GITHUB_REPO = "damiththa/water-me-please"
EVENT_TYPE = "flic_water_all_dev"
